name: Tests

on:
  schedule:
    - cron: '0 7 * * *'
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run mode (no deletions)'
        required: true
        default: 'true'

jobs:
  tests:
    permissions:
      contents: write
      issues: write
    uses: peviitor-scrapers/Brewtality-3-16/.github/workflows/tests-js-reusable.yml@main
